services:
  backend:
    build: backend
    tty: true
    secrets:
      - db-password
    depends_on:
      - db
  db:
    image: mariadb
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=minibook_development
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
    expose:
      - 3306
    ports:
      - 3306:3306
  proxy:
    build: proxy
    ports:
      - 80:80
    depends_on:
      - backend
volumes:
  db-data: null
secrets:
  db-password:
    file: db/password.txt
